name: Publish common lib

on:
  workflow_dispatch:
    inputs:
      version:
        description: Package version
        type: choice
        options: 
          - major
          - minor
          - patch
        default: "patch"

jobs:
  test-common:
    uses: ./.github/workflows/test-project.yml
    secrets: inherit
    with:
      project_dir: packages/common

  publish-common:
    needs: test-common
    uses: ./.github/workflows/publish-node-package.yml
    secrets: inherit
    with:
      name: common
      project_dir: packages/common
      version: ${{ inputs.version }}
      public: true
